// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlI4dq8p1PmJxBcjSyahRbU43NZbEp75o',
    appId: '1:439472327547:web:db6eb6f823de400c504bde',
    messagingSenderId: '439472327547',
    projectId: 'flutter-chat-application-3e57f',
    authDomain: 'flutter-chat-application-3e57f.firebaseapp.com',
    storageBucket: 'flutter-chat-application-3e57f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt9en42OnxMwgzHVOQhNvJHtgxXlzZyAw',
    appId: '1:439472327547:android:fd9dd87e84d90f71504bde',
    messagingSenderId: '439472327547',
    projectId: 'flutter-chat-application-3e57f',
    storageBucket: 'flutter-chat-application-3e57f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDuuvq1NPF8NrV11o0RXRIU3RyDuKhNv4',
    appId: '1:439472327547:ios:061988594b52f5c2504bde',
    messagingSenderId: '439472327547',
    projectId: 'flutter-chat-application-3e57f',
    storageBucket: 'flutter-chat-application-3e57f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDuuvq1NPF8NrV11o0RXRIU3RyDuKhNv4',
    appId: '1:439472327547:ios:061988594b52f5c2504bde',
    messagingSenderId: '439472327547',
    projectId: 'flutter-chat-application-3e57f',
    storageBucket: 'flutter-chat-application-3e57f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlI4dq8p1PmJxBcjSyahRbU43NZbEp75o',
    appId: '1:439472327547:web:1427ed08a3c9220f504bde',
    messagingSenderId: '439472327547',
    projectId: 'flutter-chat-application-3e57f',
    authDomain: 'flutter-chat-application-3e57f.firebaseapp.com',
    storageBucket: 'flutter-chat-application-3e57f.firebasestorage.app',
  );

}